# Generated by Django 3.0.3 on 2020-12-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfoid',
            name='email',
        ),
        migrations.AlterField(
            model_name='userinfoid',
            name='id_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
