# Generated by Django 3.0.3 on 2020-12-09 12:24

from django.db import migrations, models
import django.db.models.deletion
import pollingapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pollingapp', '0002_auto_20201204_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoid',
            name='id_number',
            field=models.PositiveIntegerField(unique=True, validators=[pollingapp.models.checkID]),
        ),
        migrations.CreateModel(
            name='PartyVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=15)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pollingapp.UserInfoID')),
            ],
        ),
    ]
